Alt+- add video-zoom -0.25
Alt+= add video-zoom 0.25
9 add volume -5
0 add volume 5
WHEEL_UP add volume 5
WHEEL_DOWN add volume -5
ctrl+r cycle_values video-rotate "90" "180" "270" "0"
f5 set contrast 0;set brightness 0;set gamma 0;set saturation 0;set hue 0;set sub-pos 100;set sub-scale 1;set panscan 0;set zoom 0;show-text default
n change-list glsl-shaders toggle "~~/adaptive-sharpen.glsl"
# n change-list glsl-shaders toggle "~~/FSR.glsl"