#Profile which sets some quality settings (Recommended)
# profile=high-quality
profile=quality
# Video
vo=gpu-next
scale-antiring=0.6
gpu-api=opengl
# Enable best HW decoder; turn off for software decoding
hwdec=auto

# Audio
# mute
volume=25
volume-gain=0.5

#Name format you want to save the pictures
screenshot-template="%x/Screenshot-%F-T%wH.%wM.%wS.%wT-F%{estimated-frame-number}"

#Don't close the player after finishing the video
keep-open=yes

#The last position of your video is saved when quitting mpv
save-position-on-quit=yes

#Start mpv with a % smaller resolution of your screen
autofit=75%

#Force seeking (if seeking doesn't work)
force-seekable=yes

#Cursor hide in ms
cursor-autohide=100

#Generate a playlist from same files in the same directory
autocreate-playlist=same

auto-window-resize=yes

loop-file=inf

screen=2

#Debanding on all videos
#Set it "no" if you rather handle it with profiles or a key shortcut (recommended)
#Debanding videos where it isn't needed can result in detail loss
deband=yes

#Deband steps (More = Better quality, but higher GPU cost)
deband-iterations=4

#Deband strength (More = Less banding, but more detail loss)
deband-threshold=48

#Deband range (More = Less banding, but higher GPU cost)
deband-range=24

#Dynamic Grain (More = More dynamic grain)
#Set it to "0" in case you prefer the static grain shader or don't like grain
deband-grain=16
